# Generated by roxytest: Do not edit by hand!

# File R/surv_max.r: @tests

test_that("Function surv_max() @ L26", {
  dist1 <- define_surv_param(dist = 'weibull', shape = 1.2, scale = 1.3)
  dist2 <- define_surv_cure(dist = 'weibull', theta = 0.2, shape = 1.2, scale = 1.3)
  
  expectedResult <- list(dists = list(dist1, dist2))
  class(expectedResult) <- c('surv_max', 'surv_combined', 'surv_dist')
  
  expect_error(surv_max(), "Please define at least one survival distribution", fixed = TRUE)
  expect_error(surv_max(5,5), "Survival distributions of index(s) 1, 2 are invalid", fixed = TRUE)
  expect_equal(surv_max(dist1,dist2), expectedResult)
})

