# Generated by roxytest: Do not edit by hand!

# File R/set_covariates.r: @tests

test_that("Function surv_prob.surv_model() @ L96", {
  fs <- flexsurvreg(Surv(rectime, censrec)~group, data = flexsurv::bc, dist = 'weibull')
  model1 <- set_covariates(fs, group = 'Good')
  expect_equal(
   surv_prob(model1, seq_len(100)),
   summary(fs, type = 'survival', t = seq_len(100), tidy = TRUE, newdata = data.frame(group = 'Good'))$est
  )
  fs <- flexsurvreg(Surv(rectime, censrec)~group, data = flexsurv::bc, dist = 'weibull')
  model2 <- set_covariates(fs, data.frame(group = c('Good', 'Medium', 'Poor')))
  expect_equal(
   surv_prob(model2, seq_len(100)),
   summary(fs, type = 'survival', t = seq_len(100), tidy = TRUE) %>%
       group_by(time) %>%
       summarize(est = mean(est)) %>% .$est
  )
})


test_that("Function print.surv_model() @ L114", {
  fs <- flexsurvreg(Surv(rectime, censrec)~group, data = flexsurv::bc, dist = 'weibull')
  model <- set_covariates(fs, group = 'Good')
  expect_output(
   print(model),
   'Predicted survival from fitted model for specified cohort'
  )
  expect_output(
   print(model),
   'flexsurvreg'
  )
})

