# Generated by roxytest: Do not edit by hand!

# File R/error.r: @tests

test_that("Function get_error_msg() @ L8", {
  expect_equal(get_error_msg('missing_parameters', dist = 'a', params = 'b'), 'Error defining a distribution, parameters missing from function call: b.')
})

