# Generated by roxytest: Do not edit by hand!

# File R/herosurv.r: @tests

test_that("Function .onLoad() @ L35", {
  options(
   list(
       herosurv.show_call_signature_in_errors = NULL,
       herosurv.show_call_signature_in_warnings = NULL
   )
  )
  .onLoad()
  expect_equal(
   c(
       'herosurv.show_call_signature_in_errors',
       'herosurv.show_call_signature_in_warnings'
   ) %in% names(options()),
   c(TRUE, TRUE)
  )
})

